CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "biography" text,
  "avatar_url" varchar(255),
  "avatar_storage_path" varchar(255),
  "role" varchar(20) NOT NULL DEFAULT 'regular',
  "status" varchar(20) NOT NULL DEFAULT 'active',
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "posts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "title" varchar(120) NOT NULL,
  "description" text,
  "comments_enabled" boolean NOT NULL DEFAULT true,
  "status" varchar(20) NOT NULL DEFAULT 'active',
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "media" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" integer NOT NULL,
  "type" varchar(20) NOT NULL,
  "url" varchar(255) NOT NULL,
  "license" varchar(30) NOT NULL,
  "watermark_text" varchar(100),
  "created_at" timestamp NOT NULL
);

CREATE TABLE "comments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "content" text NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'active',
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "ratings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "points" integer NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "follows" (
  "follower_id" integer NOT NULL,
  "following_id" integer NOT NULL,
  "created_at" timestamp NOT NULL,
  PRIMARY KEY ("follower_id", "following_id")
);

CREATE TABLE "reports" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reporter_id" integer NOT NULL,
  "reported_user_id" integer,
  "post_id" integer,
  "comment_id" integer,
  "reason" varchar(100) NOT NULL,
  "description" text,
  "status" varchar(20) NOT NULL DEFAULT 'pending',
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "interests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "post_id" integer NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "collections" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "name" varchar(80) NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL
);

CREATE TABLE "collection_items" (
  "collection_id" integer NOT NULL,
  "post_id" integer NOT NULL,
  "created_at" timestamp NOT NULL,
  PRIMARY KEY ("collection_id", "post_id")
);

CREATE TABLE "tags" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "post_tags" (
  "post_id" integer NOT NULL,
  "tag_id" integer NOT NULL,
  PRIMARY KEY ("post_id", "tag_id")
);

CREATE TABLE "notifications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "actor_id" integer,
  "type" varchar(30) NOT NULL,
  "is_read" boolean NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "notification_comments" (
  "notification_id" integer PRIMARY KEY,
  "comment_id" integer NOT NULL
);

CREATE TABLE "notification_ratings" (
  "notification_id" integer PRIMARY KEY,
  "rating_id" integer NOT NULL
);

CREATE TABLE "notification_follows" (
  "notification_id" integer PRIMARY KEY,
  "follower_id" integer NOT NULL
);

CREATE TABLE "notification_interests" (
  "notification_id" integer PRIMARY KEY,
  "interest_id" integer NOT NULL
);

CREATE TABLE "notification_reports" (
  "notification_id" integer PRIMARY KEY,
  "report_id" integer NOT NULL
);

CREATE UNIQUE INDEX ON "ratings" ("post_id", "user_id");

CREATE UNIQUE INDEX ON "interests" ("user_id", "post_id");

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "media" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ratings" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ratings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "follows" ADD FOREIGN KEY ("follower_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "follows" ADD FOREIGN KEY ("following_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reports" ADD FOREIGN KEY ("reporter_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reports" ADD FOREIGN KEY ("reported_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reports" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reports" ADD FOREIGN KEY ("comment_id") REFERENCES "comments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "interests" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "interests" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "collections" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "collection_items" ADD FOREIGN KEY ("collection_id") REFERENCES "collections" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "collection_items" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "post_tags" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "post_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("actor_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notification_comments" ADD FOREIGN KEY ("notification_id") REFERENCES "notifications" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notification_comments" ADD FOREIGN KEY ("comment_id") REFERENCES "comments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notification_ratings" ADD FOREIGN KEY ("notification_id") REFERENCES "notifications" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notification_ratings" ADD FOREIGN KEY ("rating_id") REFERENCES "ratings" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notification_follows" ADD FOREIGN KEY ("notification_id") REFERENCES "notifications" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notification_follows" ADD FOREIGN KEY ("follower_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notification_interests" ADD FOREIGN KEY ("notification_id") REFERENCES "notifications" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notification_interests" ADD FOREIGN KEY ("interest_id") REFERENCES "interests" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notification_reports" ADD FOREIGN KEY ("notification_id") REFERENCES "notifications" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notification_reports" ADD FOREIGN KEY ("report_id") REFERENCES "reports" ("id") DEFERRABLE INITIALLY IMMEDIATE;
